# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ElyPrismLauncher.ElyPrismLauncher.MSVC
PackageVersion: 11.1.1
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: elyprismlauncher.exe
  InstallerUrl: https://github.com/ElyPrismLauncher/Launcher/releases/download/11.1.1/PineconeMC-Windows-MSVC-arm64-Portable-11.1.1.zip
  InstallerSha256: 56FC0CD8739AAD6A114A8A973D762D6FE2F7D8EBEE57CC596AB0E930B0897466
- Architecture: neutral
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: elyprismlauncher.exe
  InstallerUrl: https://github.com/ElyPrismLauncher/Launcher/releases/download/11.1.1/PineconeMC-Windows-MSVC-Portable-11.1.1.zip
  InstallerSha256: 2690EA666E31003D50CAF85A20E8A09D22017E54A6983241A2B9337F0B994A01
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/ElyPrismLauncher/Launcher/releases/download/11.1.1/PineconeMC-Windows-MSVC-Setup-11.1.1.exe
  InstallerSha256: 828294FCD8C71C33C307DC7971936A5B8801DD02E32DDC6648E87CB4A92F5562
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: ElyPrismLauncher
  AppsAndFeaturesEntries:
  - ProductCode: ElyPrismLauncher
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\ElyPrismLauncher'
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/ElyPrismLauncher/Launcher/releases/download/11.1.1/PineconeMC-Windows-MSVC-arm64-Setup-11.1.1.exe
  InstallerSha256: 0D3841DE8FD138F3C0E57621638E6DEDE7485108F6BD44479F645BB4E25B6286
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
  ProductCode: ElyPrismLauncher
  AppsAndFeaturesEntries:
  - ProductCode: ElyPrismLauncher
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\ElyPrismLauncher'
ManifestType: installer
ManifestVersion: 1.12.0
