# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FreesmTeam.FreesmLauncher
PackageVersion: 2.3.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: FreesmLauncher
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- Publisher: Freesm Launcher Contributors
  ProductCode: FreesmLauncher
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\FreesmLauncher'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/FreesmTeam/FreesmLauncher/releases/download/2.3.1/FreesmLauncher-Windows-MSVC-Setup-2.3.1.exe
  InstallerSha256: F878B94482CB7CD10892D0B4AAF85DF2829546F5B28ECC9788DFC3DB7C5BD8F9
- Architecture: arm64
  InstallerUrl: https://github.com/FreesmTeam/FreesmLauncher/releases/download/2.3.1/FreesmLauncher-Windows-MSVC-arm64-Setup-2.3.1.exe
  InstallerSha256: EA12CECBC0002A3E7BC4CD5D6043D3B3A9B65B37297B7BA4084DEA45276C62D9
ManifestType: installer
ManifestVersion: 1.12.0
