# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: farion1231.CC-Switch
PackageVersion: 4.0.5
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-08
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Programs/CC Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.5/CC-Switch-v4.0.5-Windows.msi
  InstallerSha256: 473E85B39748E6C602BE28E7FB66D4967C5EF9F8C4905AB4ABC2B026BE475274
  ProductCode: '{AC677C39-9CA8-42BC-8CE1-EE2EC2533879}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{AC677C39-9CA8-42BC-8CE1-EE2EC2533879}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
- Architecture: arm64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.5/CC-Switch-v4.0.5-Windows-arm64.msi
  InstallerSha256: F5E2FAFC291BD16E18847DABB38987533237A50BAE71554EEF2A5DC88597B1A6
  ProductCode: '{E9F59894-CCE2-4A6E-A7BC-E4BB0AE03AC2}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{E9F59894-CCE2-4A6E-A7BC-E4BB0AE03AC2}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
ManifestType: installer
ManifestVersion: 1.12.0
