# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: farion1231.CC-Switch
PackageVersion: 4.0.4
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-07
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Programs/CC Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.4/CC-Switch-v4.0.4-Windows.msi
  InstallerSha256: D6DD46349FD0EC8FB76DAC77FC8F2B95EB74CDEA63A9ED1966E3E79F50BE59FD
  ProductCode: '{F0D32791-1E7A-4F5C-8103-9365E4E15AFD}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{F0D32791-1E7A-4F5C-8103-9365E4E15AFD}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
- Architecture: arm64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.4/CC-Switch-v4.0.4-Windows-arm64.msi
  InstallerSha256: 8BFFFB4443AA369DA8A3436666E34E697CA3B772577B3684E1AD7E2F96C8136B
  ProductCode: '{85576150-A92A-4FC7-8B50-88AEF22B37E1}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{85576150-A92A-4FC7-8B50-88AEF22B37E1}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
ManifestType: installer
ManifestVersion: 1.12.0
