# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: farion1231.CC-Switch
PackageVersion: 4.0.6
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-09
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Programs/CC Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.6/CC-Switch-v4.0.6-Windows.msi
  InstallerSha256: B5FA9EF681D74C9E38BB7131441552262C93F30568BD6B723DFA1905867616B8
  ProductCode: '{2D4C82AE-6491-4C84-A712-A50F762E5731}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{2D4C82AE-6491-4C84-A712-A50F762E5731}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
- Architecture: arm64
  InstallerUrl: https://github.com/farion1231/cc-switch/releases/download/v4.0.6/CC-Switch-v4.0.6-Windows-arm64.msi
  InstallerSha256: F17E00DEE55E8D2B1EAD202C8ECDCE2BDBEA7A6F3EA781F7057210C398E5494C
  ProductCode: '{6A13AB0C-A06D-4FC5-BE7C-E8C8B867E4F3}'
  AppsAndFeaturesEntries:
  - Publisher: ccswitch
    ProductCode: '{6A13AB0C-A06D-4FC5-BE7C-E8C8B867E4F3}'
    UpgradeCode: '{55F90CA4-617A-5350-A7CF-F6F24252866B}'
ManifestType: installer
ManifestVersion: 1.12.0
