checkUrl: https://ultraviewer.net/changelogs.html
versionRegex: 'Version \K\d+(?:\.\d+){2}'
urlTemplates:
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_en.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_es.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_ir.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_fr.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_id.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_it.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_jp.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_kr.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_pl.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_pt.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_ro.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_ru.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_sr.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_th.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_tr.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_vi.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_cn.exe
  - https://dl2.ultraviewer.net/UltraViewer_setup_{VERSION_SHORT}_tw.exe
urlTemplateValues:
  VERSION_SHORT: 'Version \K\d+\.\d+'
rootInstallerProperties:
  - ProductCode
