# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LanRhyme.MicYou
PackageVersion: 2.1.0
InstallerLocale: zh-CN
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{C8E6D8A6-3A1B-4E38-B76B-C9DB2A0058C0}_is1'
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- ProductCode: '{C8E6D8A6-3A1B-4E38-B76B-C9DB2A0058C0}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/LanRhyme/MicYou/releases/download/v2.1.0/MicYou-Win-2.1.0-installer.exe
  InstallerSha256: 4C558533C2F6C8BF330C9AD823DB77D61FB8CE863F2721014920126255D20C02
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/LanRhyme/MicYou/releases/download/v2.1.0/MicYou-Win-2.1.0-installer.exe
  InstallerSha256: 4C558533C2F6C8BF330C9AD823DB77D61FB8CE863F2721014920126255D20C02
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\MicYou'
ManifestType: installer
ManifestVersion: 1.12.0
